### ISSUE TITLE
Epic: Email capture with certificate (User Flow attached)

### ISSUE THREAD

**Issue by anothermadeline** [rmx-party/choodle#151]
# Criteria
As a choodler, I want to have a validation of my work, so that I can prove my authorship

## Epic Overview – Tasks
_Tasks will be broken down into more detailed tickets and linked here once added to repo_

`Email-caputre modal` #157 
* Modal "Enter your email to claim ownership"
* All modal copy must be in Sanity CMS

`Email generation`
* Email delivery service provider that supports blockchain projects #150
* Generate png of certificate from Choodle and design #153 #161 
* Email copy must be in Sanity CMS #152 
* Attach png to email #152 
* Save png with evergreen link (accessible via Sanity)

`UI refresh`
* Remove Fest copy from production #160

## Design Reference
- [Design review in Figjam (tentative) ↗ ](https://www.figma.com/file/qPFUTJ68JuVWbShzFAKfGj/Email-Capture-Test?type=whiteboard&node-id=304%3A101&t=gOcNb7IsA9RUfUN7-1)

![Image](https://github.com/rmx-party/choodle/assets/120132882/006ff761-ce7e-42c8-bbea-52a2090941fa)

**Comment by paigel** [comment]
All tasks related to this epic have been separated into their own tickets (referenced in description above). I am closing this ticket as a duplicate.
