### ISSUE TITLE
CMS: As an admin, I can edit email copy that prevents tech/design debt

### ISSUE THREAD

**Issue by anothermadeline** [rmx-party/choodle#152]
# Criteria
Given sending users an email with body copy, then an admin needs to edit that copy

Reference #163 

## Tasks
- [x] See copy needs in #163 
- [x] Add plain-text editing to Sanity CMS for email body copy

## Design Reference
**SOT for Copy**
[in Notion](https://www.notion.so/rmxparty/SOT-Email-Certificate-of-Authenticity-174c18bc24b446cf82ab0d6a17dca029?pvs=4)

**Visual reference**
[in Figma](https://www.figma.com/file/QigRM4CnB2EhfPWa4ZJZIZ/Choodle-Beta?type=design&node-id=103%3A66474&mode=design&t=njsooH0di9NMHJ7a-1)

**Comment by brandondees** [comment]
@paigel yeah we don't see any issues there

**Comment by paigel** [comment]
completed ✅
