### ISSUE TITLE
Discovery: Investigate PNG in body of email and as attachment

### ISSUE THREAD

**Issue by anothermadeline** [rmx-party/choodle#153]
We'd like to send users a plain-text email with links that includes a PNG image of their certificate. The certificate has text and an image of the user's choodle.

Look into feasible ways to attach the certification as a PNG to the email as well as embedding the PNG into the body of the email (small enough so it'll fetch and still render well). 

Optimize for Gmail. 

- [x] test image rendering options (PDF?)
- [x] how to attach to email
- [x] how to add to email body

**Comment by brandondees** [comment]
attachments are sorted out, no real problem there

seems like inline rendering using a data url in the email body, works in some email clients but not in others (e.g. gmail truncates the message based on raw length, and leaves the base64 string trailing in plaintext as invalid markup.

**Comment by brandondees** [comment]
we're exploring uploading the cert to sanity and then either inlining a rescaled version into the email body or just using an external image source so the raw image data isn't eating up gmail's content size limit. having a copy in sanity may be useful for other purposes anyway.
