### ISSUE TITLE
Hook up staging environment

### ISSUE THREAD

**Issue by anothermadeline** [rmx-party/choodle#156]

**Comment by brandondees** [comment]
staging environment was already set up on vercel but today we turned off auto-deployment on the production configuration from `main` and set it to reference a `production` branch instead.

**Comment by brandondees** [comment]
https://choodle-staging.vercel.app/ is where we should be looking at work in progress between production updates.

**Comment by brandondees** [comment]
and https://choodle-sanity-studio-staging.vercel.app/desk for the sanity studio
